//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminOrder
    {
        public int AdminOrderID { get; set; }
        public int UserID { get; set; }
        public int FoodID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderSituation { get; set; }
        public Nullable<int> OrderAmount { get; set; }
        public Nullable<int> OrderAddress { get; set; }
        public string OrderPhone { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual users users { get; set; }
    }
}
