//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.AdminOrder = new HashSet<AdminOrder>();
            this.Inventory = new HashSet<Inventory>();
            this.orders = new HashSet<orders>();
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int FoodID { get; set; }
        public string FoodCategory { get; set; }
        public string FoodName { get; set; }
        public int FoodPrice { get; set; }
        public string FoodCal { get; set; }
        public string FoodFat { get; set; }
        public string FoodCar { get; set; }
        public string FoodPro { get; set; }
        public string FoodSalt { get; set; }
        public string FoodSugar { get; set; }
        public string FoodMin { get; set; }
        public string FoodPicture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminOrder> AdminOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
