//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int FoodID { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual users users { get; set; }
    }
}
